/**
 * 日程数据结构与来源 `0422-tingkai-schedule/src/vv-assistant/types.ts` 中 `VvScheduleItem` 对齐（演示子集）。
 */
export type Schedule0422AttendeeRsvp = "accepted" | "declined" | "tentative" | "pending"

export type Schedule0422Item = {
  id: string
  title: string
  start: string
  end: string
  time: string
  location: string
  attendees: string[]
  reminder: string
  notes: string
  /** `confirmed` | `cancelled` | `deleted`（演示） */
  status: string
  dateLabel: string
  linkedMeetingId: string | null
  organization?: string
  organizerName?: string
  calendarDate?: string
  calendarTypeId?: string
  meetingNumber?: string
  attendeeRsvp?: Partial<Record<string, Schedule0422AttendeeRsvp>>
  /**
   * 列表行角标（演示）：如「进行中」「未开始」「待确认」。
   * 不设则仅根据时间与 RSVP 推导「已结束」「未响应」等。
   */
  displayHint?: string
}

/** 与来源 seeds 中 `SCHEDULE_CURRENT_USER_NAME` 一致，用于组织人 / RSVP 逻辑 */
export const SCHEDULE_0422_CURRENT_USER = "陈廷凯"

export const SCHEDULE_0422_CONVERSATION_ID = "c-schedule-0422-demo"

/** 顶栏组织 id：与 `schedule0422NavOrganizations` 一致 */
export const SCHEDULE_0422_ORG_ID_MING_SHI = "ming-shi-edu"
export const SCHEDULE_0422_ORG_ID_PERSONAL = "personal"

export function schedule0422InitialItems(): Schedule0422Item[] {
  return [
    {
      id: "sch-1",
      title: "数据看板需求评审",
      start: "11:00",
      end: "12:00",
      time: "11:00 - 12:00",
      location: "会议室 B",
      attendees: ["陈廷凯", "李四"],
      reminder: "15 分钟前提醒",
      notes: "评审数据看板需求范围与排期。",
      status: "confirmed",
      dateLabel: "周二",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-07",
      calendarTypeId: "cal-default",
      meetingNumber: "715168009",
      attendeeRsvp: { 李四: "accepted" },
    },
    {
      id: "sch-2",
      title: "合规培训（全员）",
      start: "09:00",
      end: "10:30",
      time: "09:00 - 10:30",
      location: "线上",
      attendees: ["陈廷凯", "全员"],
      reminder: "开始时提醒",
      notes: "",
      status: "confirmed",
      dateLabel: "周三",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-08",
      calendarTypeId: "cal-default",
    },
    {
      id: "sch-3",
      title: "客户回访（华东）",
      start: "14:00",
      end: "15:00",
      time: "14:00 - 15:00",
      location: "线上协作",
      attendees: ["陈廷凯", "王五"],
      reminder: "",
      notes: "",
      status: "confirmed",
      dateLabel: "周三",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-08",
      calendarTypeId: "cal-default",
    },
    {
      id: "sch-4",
      title: "文档规范同步",
      start: "16:00",
      end: "17:00",
      time: "16:00 - 17:00",
      location: "会议室 A",
      attendees: ["陈廷凯", "产品组"],
      reminder: "5 分钟前提醒",
      notes: "",
      status: "deleted",
      dateLabel: "周三",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-08",
      calendarTypeId: "cal-fitness",
    },
    {
      id: "sch-5",
      title: "教研组例会（排课）",
      start: "10:00",
      end: "11:00",
      time: "10:00 - 11:00",
      location: "会议室 C",
      attendees: ["陈廷凯", "赵六", "孙七"],
      reminder: "15 分钟前提醒",
      notes: "讨论下周排课与教室占用。",
      status: "confirmed",
      dateLabel: "周二",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-22",
      calendarTypeId: "cal-default",
      displayHint: "未开始",
    },
    {
      id: "sch-6",
      title: "渠道合作方案评审",
      start: "14:00",
      end: "15:30",
      time: "14:00 - 15:30",
      location: "线上",
      attendees: ["陈廷凯", "王五", "外部顾问"],
      reminder: "开始时提醒",
      notes: "",
      status: "confirmed",
      dateLabel: "周二",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-22",
      calendarTypeId: "cal-default",
      displayHint: "进行中",
    },
    {
      id: "sch-7",
      title: "预算调整沟通（待你确认）",
      start: "09:30",
      end: "10:15",
      time: "09:30 - 10:15",
      location: "小会议室",
      attendees: ["陈廷凯", "财务-周敏"],
      reminder: "1 小时前提醒",
      notes: "",
      status: "confirmed",
      dateLabel: "周三",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "财务-周敏",
      calendarDate: "2026-04-23",
      calendarTypeId: "cal-default",
      attendeeRsvp: { 陈廷凯: "pending" },
      displayHint: "待确认",
    },
    {
      id: "sch-8",
      title: "产品双周迭代计划",
      start: "15:00",
      end: "16:00",
      time: "15:00 - 16:00",
      location: "会议室 A",
      attendees: ["陈廷凯", "产品组"],
      reminder: "",
      notes: "",
      status: "confirmed",
      dateLabel: "周三",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-23",
      calendarTypeId: "cal-default",
      displayHint: "未开始",
    },
    {
      id: "sch-9",
      title: "新学员试听 · 数学",
      start: "10:30",
      end: "11:30",
      time: "10:30 - 11:30",
      location: "教室 302",
      attendees: ["陈廷凯", "家长代表"],
      reminder: "30 分钟前提醒",
      notes: "",
      status: "confirmed",
      dateLabel: "周四",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-24",
      calendarTypeId: "cal-default",
      displayHint: "未开始",
    },
    {
      id: "sch-10",
      title: "教学服务质量复盘",
      start: "13:30",
      end: "15:00",
      time: "13:30 - 15:00",
      location: "大会议室",
      attendees: ["陈廷凯", "教研组"],
      reminder: "开始时提醒",
      notes: "",
      status: "confirmed",
      dateLabel: "周四",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-24",
      calendarTypeId: "cal-default",
      displayHint: "进行中",
    },
    {
      id: "sch-11",
      title: "市场活动物料定稿",
      start: "16:30",
      end: "17:00",
      time: "16:30 - 17:00",
      location: "设计工位区",
      attendees: ["陈廷凯", "市场-小刘"],
      reminder: "",
      notes: "",
      status: "confirmed",
      dateLabel: "周四",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "市场-小刘",
      calendarDate: "2026-04-24",
      calendarTypeId: "cal-default",
      displayHint: "待确认",
      attendeeRsvp: { 陈廷凯: "tentative" },
    },
    {
      id: "sch-12",
      title: "一对一 · 家长沟通",
      start: "09:00",
      end: "09:45",
      time: "09:00 - 09:45",
      location: "线上",
      attendees: ["陈廷凯", "家长王女士"],
      reminder: "15 分钟前提醒",
      notes: "",
      status: "confirmed",
      dateLabel: "周五",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-25",
      calendarTypeId: "cal-default",
      displayHint: "未开始",
    },
    {
      id: "sch-13",
      title: "技术债清理冲刺（站会）",
      start: "11:00",
      end: "11:30",
      time: "11:00 - 11:30",
      location: "站会区",
      attendees: ["陈廷凯", "研发组"],
      reminder: "开始时提醒",
      notes: "",
      status: "confirmed",
      dateLabel: "周五",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-25",
      calendarTypeId: "cal-default",
      displayHint: "进行中",
    },
    {
      id: "sch-14",
      title: "端午放假前安全检查",
      start: "15:30",
      end: "16:30",
      time: "15:30 - 16:30",
      location: "全校巡查",
      attendees: ["陈廷凯", "后勤"],
      reminder: "1 天前提醒",
      notes: "",
      status: "confirmed",
      dateLabel: "周五",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-25",
      calendarTypeId: "cal-default",
      displayHint: "未开始",
    },
    {
      id: "sch-15",
      title: "跨部门需求澄清",
      start: "10:00",
      end: "11:30",
      time: "10:00 - 11:30",
      location: "会议室 B",
      attendees: ["陈廷凯", "运营", "研发"],
      reminder: "",
      notes: "",
      status: "confirmed",
      dateLabel: "周六",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-26",
      calendarTypeId: "cal-default",
      displayHint: "待确认",
      attendeeRsvp: { 陈廷凯: "pending" },
    },
    {
      id: "sch-16",
      title: "读书分享会（可选参加）",
      start: "19:00",
      end: "20:30",
      time: "19:00 - 20:30",
      location: "图书馆",
      attendees: ["陈廷凯", "自愿报名"],
      reminder: "",
      notes: "",
      status: "confirmed",
      dateLabel: "周六",
      linkedMeetingId: null,
      organization: "名师教育",
      organizerName: "陈廷凯",
      calendarDate: "2026-04-26",
      calendarTypeId: "cal-default",
      displayHint: "未开始",
    },
    {
      id: "sch-personal-1",
      title: "个人：跑步计划",
      start: "18:30",
      end: "19:00",
      time: "18:30 - 19:00",
      location: "户外",
      attendees: ["陈廷凯"],
      reminder: "",
      notes: "个人日程演示。",
      status: "confirmed",
      dateLabel: "今天",
      linkedMeetingId: null,
      organization: "个人",
      organizerName: "陈廷凯",
      calendarDate: (() => {
        const d = new Date()
        return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`
      })(),
      calendarTypeId: "cal-default",
    },
  ]
}
